# Ansible playbook to update all apt packages on the target nodes.
---
- hosts: all

  become: true

  tasks:
    - name: Update all apt packages
      apt:
        upgrade: yes
        update_cache: yes